version: '3.5'


volumes:
  wp_db:
    driver_opts:
      o: bind
      device: /Users/ouseqqam/Desktop/data
  db_data:

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
       - db_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    volumes:
      - wp_db:/var/www/html
    env_file:
      - .env
    networks:
      - inception
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - wp_db:/var/www/html
    ports:
      - 443:443
    networks:
      - inception

networks:
  inception:
    name: inception
    
