version: '3'


volumes:
  wp_db:
    driver_opts:
      o: bind
      device: /Users/ouseqqam/Desktop/data
  db_data:

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
       - db_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - wp_db:/var/www/html
    env_file:
      - .env
    networks:
      - inception
  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - wp_db:/var/www/html
    ports:
      - 443:443
    networks:
      - inception

networks:
  inception:
    
