version: '3'


services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - wp_db:/var/www/html
    ports:
      - 443:443
  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    volumes:
       - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=inception
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=1234
  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - wp_db:/tmp/wordpress
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=1234
      - WORDPRESS_DB_NAME=inception




volumes:
  wp_db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/ouseqqam/Desktop/data
  db_data: