version: '3'


volumes:
  wp_db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/ouseqqam/Desktop/data
  db_data:

services:
  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    volumes:
       - db_data:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    volumes:
      - wp_db:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=wp
      - WORDPRESS_DB_PASSWORD=1234
      - WORDPRESS_DB_NAME=wordpress
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - wp_db:/var/www/html
    ports:
      - 443:443
