version: '3.1'

services:
  wp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - wp_data:/var/www/html
    # environment:
    #   - WORDPRESS_DB_HOST=db
    #   - WORDPRESS_DB_USER=wordpress
    #   - WORDPRESS_DB_PASSWORD=wordpress
    #   - WORDPRESS_DB_NAME=wordpress
volumes:
  wp_data:
