version: '3.1'

services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
       - dbdata:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
  
volumes:
  dbdata: